// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_agendaLanlink;

namespace WEB_agendaLanlink.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210203183220_primeiraCrud")]
    partial class primeiraCrud
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEB_agendaLanlink.Models.DataObject.TipoEndereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("tipoEnderecos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "apartamento"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "casa"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "sitio"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "galpao"
                        });
                });

            modelBuilder.Entity("WEB_agendaLanlink.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("cep")
                        .HasMaxLength(8);

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("complemento")
                        .HasMaxLength(100);

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("logradouro")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("numero")
                        .HasMaxLength(4);

                    b.Property<int>("tipoEndereco");

                    b.HasKey("Id");

                    b.ToTable("enderecos");
                });

            modelBuilder.Entity("WEB_agendaLanlink.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("celular")
                        .HasMaxLength(10);

                    b.Property<int>("cpf")
                        .HasMaxLength(11);

                    b.Property<string>("email")
                        .HasMaxLength(100);

                    b.Property<int>("enderecoId")
                        .HasMaxLength(100);

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("site")
                        .HasMaxLength(100);

                    b.Property<int>("telefone")
                        .HasMaxLength(10);

                    b.Property<int>("tipoContato");

                    b.HasKey("Id");

                    b.HasIndex("enderecoId")
                        .IsUnique();

                    b.ToTable("pessoas");
                });

            modelBuilder.Entity("WEB_agendaLanlink.Models.Pessoa", b =>
                {
                    b.HasOne("WEB_agendaLanlink.Models.Endereco", "Endereco")
                        .WithOne()
                        .HasForeignKey("WEB_agendaLanlink.Models.Pessoa", "enderecoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
